### ISSUE TITLE
Registering a new application to an API hangs in pending events

### ISSUE THREAD

**Issue by adinaclaudia** [Haufe-Lexware/wicked.haufe.io#100]
When adding an application using wicked-init, it hangs in the kong-adapter pending events with action "add" and entity type "application". Trying to subscribe that application to an API also hangs with action "add" and entity type "subscription". Because of this, subscription is unusable. 

A workaround is to restart the kong-adapter. When you do this, the events are processed and the subscription works.

**Comment by DonMartin76** [comment]
I *think* I have fixed this now. Let me know whether it occurs in wicked 1.0.0 (as soon as it's out) again.
