### ISSUE TITLE
How to run API Portal in development without docker on windows ?

### ISSUE THREAD

**Issue by deka** [Haufe-Lexware/wicked.haufe.io#102]

**Comment by DonMartin76** [comment]
Must admit that I haven't tried it in a while on Windows. What are your issues in particular?

**Comment by deka** [comment]
Thanks @DonMartin76.
If i understand i have to start with wicked.portal-kickstarter, i download project from github,
I try to run "npm install", but i have an issue with package.json dependancies : "portal-env": "file:../portal-env.tgz".
Where is this file/directory ?

**Comment by deka** [comment]
Thanks for local-update-portal-env.sh shell script. I can't use it in my Windows yet but "npm pack" is the trik.

**Comment by DonMartin76** [comment]
:+1:
