### ISSUE TITLE
Error in mail queue

### ISSUE THREAD

**Issue by devsecur** [Haufe-Lexware/wicked.haufe.io#120]
If a user enters a invalid email address, such as `name@domain.tld;name@domain.tld`, the mail queue doesn't work properly. Mailer responses with [501](https://tools.ietf.org/html/rfc5321) (Syntax error in parameters or arguments). Subsequent mails will no longer be sent. 

Debug information:
> {"date":"2018-09-20T12:38:14.968Z","module":"portal-mailer:utils","message":"- acknowledgeEvent()","delta":681,"level":"debug"}
{"date":"2018-09-20T12:38:14.968Z","module":"portal-mailer:utils","message":{"code":"EENVELOPE","response":"501 Invalid command or cannot parse to address","responseCode":501,"command":"RCPT TO"},"delta":0,"level":"error"}

The email address verification could be improved by `(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])` following [RFC 5322](https://tools.ietf.org/html/rfc5322)

**Comment by DonMartin76** [comment]
Thanks for reporting!

**Comment by DonMartin76** [comment]
Fixed in 1.0.0.beta9 in the following ways:

- Better email checking in portal-api and portal-auth (both frontend and backend)
- 501 responses are being discarded, and portal-mailer continues to send out other mail
