### ISSUE TITLE
Support for Mutual SSL with Backend API

### ISSUE THREAD

**Issue by DonMartin76** [Haufe-Lexware/wicked.haufe.io#13]
It would be convenient to have an easy means of using mutual SSL when calling backend services. Nginx has built-in support for this, but we would need to surface it in the configuration in some way, preferably by injecting it via environment variables, and not by requiring somebody to extend the Kong image.

For starters, only a single certificate will be supported; this means all backend APIs requiring mutual SSL will need to share one private key. This is not ideal, but better than nothing.

**Comment by DonMartin76** [comment]
See also Ticket https://github.com/Mashape/kong/issues/1547 for Kong. Once that is solved, doing it for wicked should be rather trivial.

**Comment by DonMartin76** [comment]
As this is getting a little pressing, we have conceived a solution for this: We want to introduce `PROXY_SSL_CERT` and `PROXY_SSL_KEY`, and if these are present when starting the `wicked.kong` container (currently only in the `:next` tag) the configuration is changed to include the `proxy_ssl_certificate[_key]` in the `nginx_kong.lua` configuration. Otherwise, the standard is kept as-is.

**Comment by DonMartin76** [comment]
To use mutual SSL, add the desired certificates to the `wicked.kong` container by passing in these two environment variables to it:

* `PROXY_SSL_KEY`
* `PROXY_SSL_CERT`

A more detailed how-to will follow. But the feature is in there for 0.10.1.

**Comment by senthilrr** [comment]
@DonMartin76, Is this change available for use now ?  if so can you share how to get this version. 0.10.1. I am trying to connect to SSL backend...
