### ISSUE TITLE
redirect_uri must be treated as optional

### ISSUE THREAD

**Issue by maksimlikharev** [Haufe-Lexware/wicked.haufe.io#143]
currently redirect_url is required as query argument, previously it was optional, and should be optional.

**Comment by DonMartin76** [comment]
Indeed: https://tools.ietf.org/html/rfc6749#section-4.1.1

And also https://tools.ietf.org/html/rfc6749#section-4.1.3 is not yet fully addressed.

**Comment by DonMartin76** [comment]
Fixed in 1.0.0-rc1.
