### ISSUE TITLE
Unable to add resposnse ratelimiting plugin.

### ISSUE THREAD

**Issue by himansingh** [Haufe-Lexware/wicked.haufe.io#144]
Hi,
I am trying to add the response-rate-limiting plugin to a plan using Kickstarter by following [configuring kong plugins documentation.](https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/configuring-kong-plugins.md)

Here is the relevant part of configuration from plans.json -
`{
      "id": "free",
      "name": "Free Plan",
      "desc": "This is a free plan.",
      "config": {
        "plugins": [
          {
            "name": "response-ratelimiting",
            "config": {
              "limits": {
                "analyze": {
                  "minute": 1,
                  "month": 4
                }
              },
              "header_name": "Count-Analyze",
              "block_on_first_violation": true
            }
          }
        ]
      }
    }`

I called API using following curl command -
`curl -kX GET https://api.company.com/get/response-headers?Count-Analyze=counting -H 'X-ApiKey: APIKEY'`
`https://api.company.com/get/response-headers?Count-Analyze=counting` is using `https://httpbin.org/response-headers` as test backend.

This neither limits the API calls nor makes any entry in response-ratelimiting_metrics table in postgres db. To ensure that plugin was enabled I added some logs in kong's response-rate-limiting code. Can anyone tell me where am I going wrong ?

Any help would be very much appreciated. Thanks!

**Comment by himansingh** [comment]
Hey @DonMartin76 ,
Actually, the backend service i.e., `response-headers` endpoint is not responding with correct headers.
So I used another custom backend service that sends `Count-Analyze= 1` header in response.
I still couldn't make it to work.

**Comment by DonMartin76** [comment]
OK, the documentation of Kong is a little tricky here. The response header you must (in your specific example) return is:

```
Count-Analyze: analyze=1
```

Set `1` to whatever you need it to be. If you have multiple rate limiters, you can comma-separate them.

And to do this with httpbin's response-header endpoint, you can do it like this:

```
$ curl -H 'X-ApiKey: (...)' https://api.company.com/get/response-headers?count-analyze=analyze=1
{
  "Content-Length": "101", 
  "Content-Type": "application/json", 
  "count-analyze": "analyze=1"
}
$ curl -H 'X-ApiKey: (...)' https://api.company.com/get/response-headers?count-analyze=analyze=1
{"message":"API rate limit exceeded for 'analyze'"}
```

So it works, it's just the docs which are a little tricky to read.

**Comment by himansingh** [comment]
Thanks, this works. I just missed it in the documentation.

**Comment by DonMartin76** [comment]
Can I close this?

**Comment by himansingh** [comment]
Yes, you can.
