### ISSUE TITLE
apim-certs.yaml prevents successful `helm upgrade` 

### ISSUE THREAD

**Issue by stackedsax** [Haufe-Lexware/wicked.haufe.io#152]
Looks like `apim-certs.yaml` falls prey to the same issue as reported here:
   * https://github.com/helm/helm/issues/4276#issuecomment-401780298

If I understand it correctly, a comment followed by a variable will ignore the variable and the following line, too.  This isn't `apim-certs.yaml`'s fault, but it prevents `helm upgrade` from running.  An upgrade will return this error:
```
Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: Object 'apiVersion' is missing in 'unstructured object has no version'
```
SImply moving the `apim-certs.yaml` out of the `templates` directory will solve the issue, but if you actually want to run that template, you're out of luck at the moment.

I'll see if I can find a fix for it.

**Comment by DonMartin76** [comment]
This should be fixed in the `wicked_1_0` branch of the Helm template; which branch did you use, or did you use the packaged one?

If so, it's weird, as it should be in there. Will investigate, thanks for reporting!

**Comment by DonMartin76** [comment]
For the sake of completeness, here's the fix (from September):

https://github.com/Haufe-Lexware/wicked.haufe.io/commit/6b56dc6e7fd93f37029d4b70715b0fd8d1d70a56#diff-1c13465e24d91aca4d3ddaa1bc3e7027

**Comment by stackedsax** [comment]
I was using the 0.12.1 branch.  I'll make the changes locally while I use this branch.  I'll return to the 1.0 branch in a little bit.  Thanks for the fix!

**Comment by DonMartin76** [comment]
The 0.12.1 branch does not contain the `portal-auth` component, so beware of that, if you're trying to use the old helm chart with the new beta.

**Comment by stackedsax** [comment]
No, I was just trying a vanilla 0.12.1 helm install, just to play around.
I'll return to the 1.0 beta helm install once I get 0.12.1 running
happily.  It looked like the 1.0 beta was going to need some work on the
helm install, so I figured I'd make sure I could get the 0.12.1 version
running before I moved ahead.  Just trying one thing at a time.


ᐧ
