### ISSUE TITLE
Can't run kubernetes deployment in development mode over http

### ISSUE THREAD

**Issue by stackedsax** [Haufe-Lexware/wicked.haufe.io#153]
I got wicked running on kubernetes with helm using the 12.1 release and I went to open the portal in the browser.  It returns this message:
```
You are running in "production" (NODE_ENV) mode, but not on https. This is not supported.
```

As far as I know, my `NODE_ENV` environment variable is actually 'k8s', not 'production'.  However, digging into the code, it seems that I should be able to convince wicked that I'm not running in production by setting the `PORTAL_NETWORK_SCHEMA` environment variable to something other than 'https'.

I have tried two methods of setting the `PORTAL_NETWORK_SCHEMA` variable:
1. forking the `wicked-sample-config` repo; updating the `network.schema` value to "http"; setting my fork as the `config.repository` value in the helm charts'  `values.json` file; and upgrading my helm release.
1. Adding a `PORTAL_NETWORK_SCHEMA` environment variable to the helm template for the portal-deployment; adding the value 'http' as the value of that new environment variable; upgrading my helm release

Neither approach has solved the issue.  Is there some other way to get past the error message without setting up kube-lego and setting up CNAMEs and all that jazz?  I just want to play around with the sample config on my kubernetes environment to see whether Wicked is what I want to use.

**Comment by DonMartin76** [comment]
The default settings of the beta release of wicked 1.0.0 should now be in a state that you can use portal.com/api.portal.com inside your /etc/hosts setting and the certificates of the Helm chart should match that.

Additionally, the "deploy" part of the Kickstarter can be used to create self signed certificates for a local docker deployment using `openssl` (must be installed; might not work as expected on Windows). This should work with the previous version as well (0.12.x), but I still recommend the beta version (soon to be RC).

**Comment by DonMartin76** [comment]
Leaving it open so we can double check this and also adapt the documentation.

**Comment by DonMartin76** [comment]
There will soon be a `wicked.box` container which will make local development of the configuration a lot easier. It will contain all wicked components in a single container (including Kong, excluding Postgres). The default for this "wicked-in-a-box" will be without "SSL and all the jazz". Will come back with more details.

Additionally, I have found an issue which prevents getting access tokens in case the authorization server cannot reach the `apiHost` from the outside of the deployment. This happens frequently in development situations, and it's not really strictly necessary to have it this way.

**Comment by DonMartin76** [comment]
It's not Kubernetes as https, but please check out [wicked-in-a-box](https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/wicked-in-a-box.md) for simple local deployments using Docker.

Would it be okay to close this?

**Comment by stackedsax** [comment]
Yep.  If I get time to come back to it, I will.  Thanks for checking in.
