### ISSUE TITLE
Support Multiple Kong Instances Using Wicked

### ISSUE THREAD

**Issue by kbhuvanamohan** [Haufe-Lexware/wicked.haufe.io#163]
Hi,

We have a scenario wherein there are two sets of applications - One in the On-Premises and other in the Cloud.

So, we want to approach this by setting up two **independent** Kong Gateway instances that are **independently configured - not in a cluster** catering to both
- On Premises
- Cloud

Please let us know if there is any option to implement this using a single wicked developer portal.

Also please share any insights how this kind of scenarios are handled in a typical wicked setup.

Thanks,
Bhuvan.

**Comment by DonMartin76** [comment]
Hi Bhuvan,

This is not a scenario which is currently supported by wicked. In this situation, I would recommend running a separate portal for both environments. You can use the same identity provider for the login, but you would not have **one** single instance of the API portal where you can see all client registrations. 

Currently, there aren't any plans either to support this type of hybrid scenario, as it requires a lot of thought, duct tape and securing the communication to enable that type of communication on and off premises. It would either be difficult or insecure (or both), and it hasn't been a priority.

Sorry.

I think some of the "big players" have this type of feature, namely 3scale and IBM, if I recall correctly.

Best, Martin

**Comment by kbhuvanamohan** [comment]
Hi Martin,
 
Thanks for the response. Let me try to add more context to see if this can be accomplished.
 
We have the scenario of two separate Kong gateways within the same private network, each publishing different set of APIs, but we want to manage and publicize them from a single Wicked portal.
 
We are looking for options to leverage a single Wicked portal so that
1) The API developers should have the ability to select which API Kong Gateway to publish their APIs and
2) The Application Consumers can seamlessly subscribe to any of these APIs
 
This way, we can maintain a single portal that can act as a catalog for all the APIs available in the Enterprise.
 
Thanks!

**Comment by kbhuvanamohan** [comment]
@miguelpoyatosmora
@karthiknaga87
Please help to provide additional information if needed and for your reference.
