### ISSUE TITLE
Kubernetes Helm Chart: It should be possible to change Postgres connection of wicked's API

### ISSUE THREAD

**Issue by DonMartin76** [Haufe-Lexware/wicked.haufe.io#167]
The Helm Chart of wicked.haufe.io is imprecise in how it's possible to change the Postgres connection. If you do not deploy Postgres as part of the chart, but separately (which is recommended), it's tricky to set the right connection parameters for wicked to use. The Postgres connection which is described in the Chart only apply **to Kong's Postgres connection**, in order to change wicked's Postgres connection, you must also update the `k8s.json` (Environment file) using the Kickstarter to include the correct values.

The Chart should contain a possibility to also set the connection parameters for wicked's connection to Postgres separately from Kong's connection.

This means that all Postgres parameters must, by default, also be  present as environment variables in `default.json` and `k8s.json`. This means that those values must be updated in an update step.

The update step must check the following:

* If the previous values are the default ones, replace them with environment variables, in default.json, k8s.json, box.json
* If all were set to default, replace them in globals.json as well

Then add the configuration possibility via Helm Chart:

* Add config values for all five Postgres parameters: Host, Port, Username, Password and Database.

**Comment by DonMartin76** [comment]
The chart now allows passing in `storage.pgHost`, `storage.pgPort`,... works by overriding `PORTAL_STORAGE_PGHOST` etc. The documentation has been adapted (the Helm chart documentation).

**Comment by ehirsch** [comment]
So there is now `storage.pgHost` and `postgres.pgHost`. The first is for wicked data and the later for kong correct? This is a little confusing don't you think?

**Comment by DonMartin76** [comment]
I admit this is confusing, yes. But if I change that now, things will/might break for existing deployments, so I chose not to.

**Comment by DonMartin76** [comment]
Fixed in 1.0.0-rc.1

**Comment by ehirsch** [comment]
I see. I did not think of that.
