### ISSUE TITLE
Audit Report or All subscriptions page for administrators and approvers 

### ISSUE THREAD

**Issue by santokhsingh** [Haufe-Lexware/wicked.haufe.io#176]
### Overview
We would like to provide the ability for approvers, and administrators to be able to view API subscription information.  

### Use Cases
- Provide a new dashboard in the wicked portal that displays information about API subscriptions.
- Ability to see approved API subscription, where the API subscription status is active.
- Approvers and Admins want to be able to view all pending and active subscriptions for which they have permissions to view.
- Ability to see all (including approved and open) API requests and the status of each.
- Provide the ability to export the table view of the dashboard into CSV file.

### Fields to Include

| Field Name      | Filterable | Sortable
| -------------- | --------- | ----------
| Status      | No       | Yes
| Application Name   | Yes        | Yes
| Registered email address for application owner | Yes | Yes
| User Name | Yes | Yes
| API ID | Yes | Yes
| API Plan | Yes | Yes

**Comment by DonMartin76** [comment]
Implemented in 1.0.0-rc.4
