### ISSUE TITLE
websocket cosmetic issue in dev portal

### ISSUE THREAD

**Issue by maksimlikharev** [Haufe-Lexware/wicked.haufe.io#177]
when I define WS API, API Settings in API URL: shows http:// or https:// 

it should really show WS:// or WSS://

there might be not cosmetic issues with swagger, best approach is to disable it or maybe play with pluggable transports.

but defining and using WS API works.

**Comment by DonMartin76** [comment]
Thanks for the heads up. Would an “API type” with “http(s)” and “wss(s)” choices be appropriate? Other types which would probably work?

**Comment by maksimlikharev** [comment]
technically kong supports proxying a lot of different types now, it can do tls and tcp traffic, but from proto point of view, http(s) or wss(s) and you cannot intermix that, it will always start as http(s) and upgrade to ws(s) and stay there. I would say it either http or ws.

**Comment by DonMartin76** [comment]
Fixed in 1.0.0-rc.4
