### ISSUE TITLE
Unable to send Email Verifications

### ISSUE THREAD

**Issue by TESAARON** [Haufe-Lexware/wicked.haufe.io#18]
Hello,

I have configured the Email section within kickstarter and require that new users receive a verification email before being able to use their account. I have tried numerous different ports (25, 465, 587) and smtp servers but no configuration seems to work. Have you encountered this issue before or do you know how I could debug the issue on the command line?

Regards,
Aaron

**Comment by DonMartin76** [comment]
Hey there, what do you see if you pass `DEBUG=portal-mailer:*` and check the logs of the `portal-mailer` container? I guess you have configured everything using the kickstarter and that the mailer is activated?

I have successfully tested with e.g. MailGun and SendGrid; which service do you use to send mail?
* Does it need authentication? 
* Are the ports open for outbound traffic?

/Martin

**Comment by TESAARON** [comment]
Hi Martin,

I'm looking at the logs in the directory '/var/log' within the mailer container but nothing of note in there. Are there any logs elsewhere I should be looking at?

Below is a screenshot of the kickstarter configuration. I able to send emails using this configuration on other java based applications (i.e. Pentaho Data Integration)

![screenshot_2016-10-13_16-41-45](https://cloud.githubusercontent.com/assets/10795276/19358085/f75a87da-9163-11e6-99c2-e4ff62f5cff0.png)

All outgoing ports are open so I'm not sure what could be stopping this from working.

Many thanks,
Aaron

**Comment by DonMartin76** [comment]
Hi Aaron, I rather meant the logs you get via `docker logs <portal mailer container id>`.

**Comment by DonMartin76** [comment]
And/or, try this for gmail:
* Tick "Force SSL"
* Use port 465

TODO for me: For known email sending providers, specify how to configure the mailer.

**Comment by TESAARON** [comment]
Hi Martin,

Below is the log from the mailer container (seems to repeat the same message every 10 seconds)

{"date":"14/Oct/2016:10:52:25 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:172.18.0.2","version":"1.1","status":"500","content-length":"245","referrer":"-","response-time":"0.323","correlation-id":"6aebae2e-f689-4490-8bb9-f73467b2ca19"}
{ [Error: utils.get("http://portal-api:3001/users/e5ded00bfe32c6930c4a5737a122b3d61945826f") return unexpected status 404] status: 404 }

Not entirely sure what this is showing up. I've tried various different combinations now but still no luck. Ports 25, 465 and 587 are open as endpoints on Azure. You can view my kickstarter configuration at http://tes-docker.cloudapp.net:3333 and the portal at https://tes-docker.cloudapp.net. Perhaps you will be able to see something here that I have not covered off. Let me know what you think.

Many thanks!
Aaron

**Comment by DonMartin76** [comment]
Okay, this is most probably at least in parts a bug. I suspect the following: A user signed up, and some time later, the user was deleted from the system. Nonetheless, the user signup was propagated to the `portal-mailer` for sending out an email, but now it cannot read the user data anymore (404).

The `portal-mailer` should react a little more forgiving here, obviously. This is simply a situation I had not yet anticipated.

The error message does show up on the API Portal's "System Health" page if you log in as an Admin user, right?

**Comment by TESAARON** [comment]
Hi Martin,

Yes the error also appears there when I log in as data@thinkevolvesolve.ie

![screenshot_2016-10-14_12-11-50](https://cloud.githubusercontent.com/assets/10795276/19387084/84b0e518-9207-11e6-9b33-e17764e8d35f.png)

**Comment by TESAARON** [comment]
Would this require a docker-compose down and a full restart you think?

**Comment by DonMartin76** [comment]
It wouldn't help. The thing here is that the `portal-mailer` reacts to a pending webhook event which is persisted (for apparent reasons), and will run into this error again; unless you mean a complete `docker-compose down` - which would also destroy all dynamic data (users, applications, subscriptions). That would definitely help, but that can't be the workaround.

If you give me another ten minutes, I'll prepare a fixed `portal-mailer` docker image for you to try out, if you feel like it.

**Comment by TESAARON** [comment]
Yes that sounds good. There is no real rush here, we are still in development mode so whenever you have the time.

Thanks again for all your help, hugely appreciated!

**Comment by DonMartin76** [comment]
Try to replace your `portal-mailer` image (in the `docker-compose.yml`) with the following image (fresh from the build pipeline): `haufelexware/wicked.portal-mailer:dev`. If that's okay, I'll think about releasing a 0.9.3 with this fix.

**Comment by TESAARON** [comment]
Hi Martin,

This worked perfectly. All systems showing healthy and email verification was sent. 

Many thanks,
Aaron

**Comment by DonMartin76** [comment]
Fixed in 0.9.3 (just released).
