### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by samuel82333** [Haufe-Lexware/wicked.haufe.io#189]
I just want to know is anyway i can visit another user profile or applications ID ( name ) from https://integration.fs.haufe.io/ ?

**Comment by DonMartin76** [comment]
Is this something which is specific to that API portal, or is it a generic question? If it is a generic question, could you re-state it, as I don't quite understand what you mean?

I will forward this question to the FS guys as well, perhaps they know.

**Comment by DonMartin76** [comment]
Closing this. This seems to be a half hearted hacking attempt to one of our API portals.
