### ISSUE TITLE
OAuth2 password grant payload must be posted using Content type "x-www-form-urlencoded"

### ISSUE THREAD

**Issue by santokhsingh** [Haufe-Lexware/wicked.haufe.io#195]
- OAuth2 password grant payload must be posted using Content type "x-www-form-urlencoded"

- Also custom parameters configured in Authentication method must be appended to payload

**Comment by santokhsingh** [comment]
Pull request https://github.com/apim-haufe-io/wicked.auth/pull/4

**Comment by DonMartin76** [comment]
Merged in 1.0.0-rc.5.
