### ISSUE TITLE
Unable to create Redirect URIs using local domains

### ISSUE THREAD

**Issue by iZydro** [Haufe-Lexware/wicked.haufe.io#196]
Hello!

For debugging purposes, I need to create an Application that uses OAuth2 Flows, and I need the redirect URI to point to a local domain. This is currently not possible in wicked. Will it be possible to add this feature?

My use case is: developing an application, using a Macbook as a host. Testing the application on Internet Explorer, using VirtualBox, on the same Macbook. Internet Explorer can find wicked on the Macbook using the IP 10.0.2.2, and I have created a DNS entry in the windows virtual machine pointing to 10.0.2.2, like application.local. But I cannot set application.local as the redirect URI.

This feature will be great just for the **wicked-box** version, as mentioned, for debugging purposes.

**Comment by DonMartin76** [comment]
OK, I can absolutely see the use case here. This will be an argument for wicked.cli (`wicked box start`) which sets an env var for the `wicked.api` container (`ALLOW_ANY_REDIRECT_URIS`). In principle, you can inject this to the `wicked.api` container in any running system, but I would certainly advice against it.

**Remark**: It probably isn't `application.local` wicked is complaining about, but the fact that it's a `http` (and not `https`) redirect URI; just checked, and `https://application.local/callback` can be registered, while `http://application.local` cannot.

**Comment by DonMartin76** [comment]
Will land in wicked 1.0.0-rc.6
