### ISSUE TITLE
Initial admin user (1) should be creatable without password

### ISSUE THREAD

**Issue by gganssauge** [Haufe-Lexware/wicked.haufe.io#20]
In my test portal I created a user in the admin group with kickstarter and removed the default admin user (id #1) from the admin group to mitigate the risk of a well-known admin user.
That had the unfortunate consequence that the portal-kong-adapter, portal-mailer and portal-chatbot containers did no longer start.
To mitigiate that risk anyway it would be useful to create the admin user without a passwort from the start - iff another admin user was configured.

**Comment by DonMartin76** [comment]
This will be fixed in two ways:

* It will be possible to remove the Admin User altogether
* Each webhook/plugin service will be able to use the `wicked-sdk` to create its own Admin machine user
* This makes it visible which webhook/service calls the API, and not only shows `userId: 1`

**Comment by DonMartin76** [comment]
This has been partly fixed: All services (kong adapter, mailer, chatbot) now use a service user to connect to the API, but it is still not possible to remove the '1' user altogether just yet.

**Comment by DonMartin76** [comment]
Parts will surface in 0.10.0, but it's still not possible to remove the `1` user yet.

**Comment by DonMartin76** [comment]
But it will be possible to define users

a) Without password
b) with a predefined customId

This makes it possible to e.g. predefine GitHub users (`"customId": "Github:<id>"`) which without any additional configuration are administrators on the portal. Very neat.

**Comment by DonMartin76** [comment]
It is since long possible to create users with a given custom ID, e.g. the Google-ID.

**Comment by DonMartin76** [comment]
The most common use cases are possible by now. Closing this.
