### ISSUE TITLE
Custom Content does not allow loading of Javascript

### ISSUE THREAD

**Issue by santokhsingh** [Haufe-Lexware/wicked.haufe.io#201]
It is sometimes required to load a javascript file from static directory i.e. from custom content space but code does not allow it.

**Use Case:**

- We need to embed a javascript file in footer so that it can be loaded for each page.
-  File is hosted in static directory i.e. in custom content space (Since it is our company specific feature)
- We trap button clicks, page loading, and link click events and send to snowplow, in order track user usage

**Comment by santokhsingh** [comment]
PR to address above: 
https://github.com/apim-haufe-io/wicked.ui/pull/44
https://github.com/apim-haufe-io/wicked.api/pull/24

**Comment by DonMartin76** [comment]
Merged. Will land in 1.0.0-rc.6, which is due as soon as wicked's Jenkins is working again :-O

**Comment by santokhsingh** [comment]
Thanks!
