### ISSUE TITLE
Reset Search Filter after action is taken

### ISSUE THREAD

**Issue by MibenCoop** [Haufe-Lexware/wicked.haufe.io#203]
### **Overview**
We would like to provide functionality when the search filter on the Applications page can maintain  previously set parameters after an action is taken on the page 

### **Description**
Current Behavior: After filtering a list and taking an action (approve/deny a request), the page refreshes without retaining the previously applied filter.

Desired Behavior: After filtering a list and taking an action (approve/deny a request), the page refreshes and retains the previously applied filter. 

### **Use Cases**
- Improved user experience

**Comment by MibenCoop** [comment]
https://github.com/apim-haufe-io/wicked.ui/pull/46

**Comment by DonMartin76** [comment]
Thank you!
