### ISSUE TITLE
ProfileEndpoint for wicked.auth not implemented yet?

### ISSUE THREAD

**Issue by Iblis** [Haufe-Lexware/wicked.haufe.io#208]
Hi! I used the Kickstarter to configure an OAuth2 endpoint and set a profileEndpoint to fetch the profile from there.
Authentication does not work and after digging into it a bit, it looks like this configuration option is not implemented yet and the auth fails because wicked tries to find the email claim in the accessToken, but it is not in there because it is expected to fetch this from the profileEndpoint.
Is this correct and if so what is the current schedule for this feature? Any help needed on that part?

**Comment by DonMartin76** [comment]
This is most probably correct, unfortunately. We were looking at fully implementing this when the support for OIDC #184 is implemented. It shouldn't be very difficult to just in the mean time implement a simple "fetch from profile end point", but I just haven't had time for it. PRs are very welcome.

**Comment by Iblis** [comment]
PR can be found here https://github.com/apim-haufe-io/wicked.auth/pull/7

**Comment by DonMartin76** [comment]
Merged, will land in 1.0.0-rc.7. THANKS!
