### ISSUE TITLE
Support for Microsoft Teams in the Chatbot

### ISSUE THREAD

**Issue by DonMartin76** [Haufe-Lexware/wicked.haufe.io#213]
It would be pretty cool if the Chatbot could also talk to a Teams webhook endpoint instead of just supporting Slack.

**Comment by Jabb0** [comment]
See a proposal here:
https://github.com/apim-haufe-io/wicked.kickstarter/tree/microsoft_teams_chatbot
and here:
https://github.com/apim-haufe-io/wicked.chatbot/tree/microsoft_teams_chatbot

Updater script to migrate old globalConfs is still missing.

**Comment by Jabb0** [comment]
Updater script now ready too:
https://github.com/apim-haufe-io/wicked.env/tree/microsoft_teams_chatbot

**Comment by DonMartin76** [comment]
Lands in rc.10
