### ISSUE TITLE
Is there a way to disable email verification in the portal?

### ISSUE THREAD

**Issue by rduran408** [Haufe-Lexware/wicked.haufe.io#220]
Is it possible to disable the email verification for new registered users?

**Comment by DonMartin76** [comment]
Yes, specify „trust users“ and the email will appear as verified without actually verifying. That should work with any identity provider. Some use this setting by default, some (like the default wicked built in one) don’t.

Please note that this setting is not a good idea in anything else than internal environments.

**Comment by rduran408** [comment]
Thanks for the quick response. Where do I specify trust users?

**Comment by DonMartin76** [comment]
In the kickstarter, under Authentication, tick the "Trust user email addresses" check box for the "local" auth method:

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/7326883/62413163-e804c400-b60c-11e9-9fad-1e841a6d50d3.png">

**Comment by DonMartin76** [comment]
Closing this - if the answer did not resolve your question feel free to reopen.
