### ISSUE TITLE
AuthServer Configuration: Hyphen in name causes login issues

### ISSUE THREAD

**Issue by Iblis** [Haufe-Lexware/wicked.haufe.io#222]
For successful login, the login route in wicked.ui checks for the state and splits it via hyphen:
https://github.com/apim-haufe-io/wicked.ui/blob/0b0973b8dc3a633cb0a424a224cf73323b89dd4a/routes/login.js#L94

This code causes issues if the auth servers name contains a hyphen. You will get a Status Code  400 (Callback state has an invalid format) because the stateList will contain more than 2 items.

Possible solutions
- Don't allow hyphens in auth server names
- Adapt code to be able to handle the situation
- Don't change code but document this convention (maybe this is even done already?)
- ...

**Comment by DonMartin76** [comment]
Ouch. Thanks for reporting. Most configuration just use a single authorization server (`default`) and thus never see this issue.

I see the second solution as the best solution; a hyphen should be allowed in the authorization server name.

Leaving this issue open for now until I (or somebody else) has time to fix this.

**Comment by DonMartin76** [comment]
This is actually happening not only if the *auth server* contains a hyphen, but also if an *auth method* contains a hyphen. And that is pretty bad.

**Comment by DonMartin76** [comment]
Will be fixed in 1.0.0-rc.10. Sorry for the inconvenience.

**Comment by DonMartin76** [comment]
(Changed state splitter to an exclamation mark instead of a hyphen; this was a little unfortunate)
