### ISSUE TITLE
Portal exits without error after inactivity

### ISSUE THREAD

**Issue by rduran408** [Haufe-Lexware/wicked.haufe.io#223]
The wicked 1.0 portal exits unexpectedly after about 2 hours of inactivity. The logs do not show any sort of error. This is the tail of the log

{"date":"04/Aug/2019:17:17:44 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:172.18.0.1","user-id":"-","user-email":"-","version":"1.1","status":"200","content-length":"490","referrer":"-","user-agent":"-","response-time":"0.537","correlation-id":"6fb091a7-4aee-49d0-b6a9-4e399a721246"}
{"date":"04/Aug/2019:17:17:44 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:10.80.154.90","user-id":"-","user-email":"-","version":"1.1","status":"200","content-length":"490","referrer":"-","user-agent":"-","response-time":"0.511","correlation-id":"6fb091a7-4aee-49d0-b6a9-4e399a721246"}
{"date":"04/Aug/2019:17:18:14 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:172.18.0.1","user-id":"-","user-email":"-","version":"1.1","status":"200","content-length":"490","referrer":"-","user-agent":"-","response-time":"0.535","correlation-id":"1ac28a8b-d6c5-47c5-a31b-fb188ae75c70"}
{"date":"04/Aug/2019:17:18:14 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:10.80.154.90","user-id":"-","user-email":"-","version":"1.1","status":"200","content-length":"490","referrer":"-","user-agent":"-","response-time":"0.484","correlation-id":"1ac28a8b-d6c5-47c5-a31b-fb188ae75c70"}
{"date":"04/Aug/2019:17:18:44 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:172.18.0.1","user-id":"-","user-email":"-","version":"1.1","status":"200","content-length":"490","referrer":"-","user-agent":"-","response-time":"0.646","correlation-id":"5350b00f-5bd3-4d5b-bdb5-905439eb2762"}
{"date":"04/Aug/2019:17:18:44 +0000","method":"GET","url":"/ping","remote-addr":"::ffff:10.80.154.90","user-id":"-","user-email":"-","version":"1.1","status":"200","content-length":"490","referrer":"-","user-agent":"-","response-time":"0.614","correlation-id":"5350b00f-5bd3-4d5b-bdb5-905439eb2762"}

**Comment by DonMartin76** [comment]
Which runtime? Kubernetes? What does kubectl describe pod say? If the pod actually quits, something on the outside ought to be wrong, as there is a process which restarts node on the inside of the container.

**Comment by DonMartin76** [comment]
Do you have any more information on this? The logs you posted above does not give any kind of hint as to why the container is restarting.

**Comment by rduran408** [comment]
The Portal is running in a single docker container. This is on a CentOs VM. It works fine until it finally times out after a period of inactivity. Everything else is up and running.

**Comment by DonMartin76** [comment]
Please check the logs of your docker engine in this case; it might give some hints as to why this happens (error codes, error conditions etc). E.g., wicked-demo.haufe.io is also a docker host deployment, and I haven't seen anything like this. I have seen other things, like full disks etc. causing all kinds of mayhem, but the API container as such typically either shows errors in the logs (e.g. Postgres connection issues) before it restarts itself.

This looks like a restart from the outside (for whatever reason).

**Comment by DonMartin76** [comment]
This _may_ be related to #231.

**Comment by DonMartin76** [comment]
Closing this for now. If you still are having these issues, or similar ones, feel free to open with more information, or to create a new issue.
