### ISSUE TITLE
Wicked - Kong API synchronization

### ISSUE THREAD

**Issue by rduran408** [Haufe-Lexware/wicked.haufe.io#224]
From reading the documentation and observing the product in action, it seems that any information (services, routes, .etc) published directly to Kong using the Kong APIs does not get reflected back in Wicked. Is there any way to synchronize this information?

**Comment by DonMartin76** [comment]
In short: No.

**Comment by DonMartin76** [comment]
A little bit longer explanation: As stated in the documentation, wicked assumes it can fully control the entire Kong instance. If you have an idea how this can be changed, and e.g. a list of exclusions can be introduced, we are of course open for that.

I don't think it makes sense for most people to have a sync step from an existing Kong configuration back to a wicked configuration - in most cases the configurations will not be compatible, and finding all the corner cases will probably not justify the effort it would take to implement this.

Closing this issue, if you want to open another one e.g. for the "exclusion list", feel free to do that.
