### ISSUE TITLE
Approver rights currently superseding Admin rights

### ISSUE THREAD

**Issue by MibenCoop** [Haufe-Lexware/wicked.haufe.io#225]
**Overview**
When an individual has approver rights and admin rights, the approver rights are superseding the admin rights.
**Description**
If a user has an administrator and approver rights, a user should see All subscriptions. Instead, approver rights overwrite admin rights

PR with changes: https://github.com/apim-haufe-io/wicked.api/pull/27
PR with tests: https://github.com/apim-haufe-io/wicked.test/pull/7

**Comment by DonMartin76** [comment]
Thank you!
