### ISSUE TITLE
Approver Permission to view application details

### ISSUE THREAD

**Issue by AbbeyW21** [Haufe-Lexware/wicked.haufe.io#226]
Overview:
As a product manager, I would like our approvers to have the ability to see the description details of the application requesting access to an API. 

Description:
Currently, the approver does not have the ability to see the requesting application description. 
We would like to change the permission of the approver role to allow for them to see the application description so they can understand the use case better and determine if it matches the pre-approved use cases of the requested API.

**Comment by DonMartin76** [comment]
Works.
