### ISSUE TITLE
Some pull requests depend on each other

### ISSUE THREAD

**Issue by MibenCoop** [Haufe-Lexware/wicked.haufe.io#228]
@DonMartin76 
There are 3 PR. They depend on each other, but the only PR to wicked.ui repo was merged. 
Could you merge the rest of the requests?

UI: https://github.com/apim-haufe-io/wicked.ui/pull/51
TEST: https://github.com/apim-haufe-io/wicked.test/pull/8
API: https://github.com/apim-haufe-io/wicked.api/pull/30

**Comment by DonMartin76** [comment]
This is done so far, right?
