### ISSUE TITLE
Restrict Ability to use special characters in application name

### ISSUE THREAD

**Issue by MibenCoop** [Haufe-Lexware/wicked.haufe.io#230]
Currently, when an application name has a special character in it, this interferes with the Portal's ability to perform properly.
We want to prevent users from using special characters in

**Comment by DonMartin76** [comment]
What was this?

**Comment by MibenCoop** [comment]
Incorrectly formulated task. It was said that it is necessary to prohibit the entry of special characters in the application name. But we came to the conclusion that the app name should be user-friendly and we can't limit users

**Comment by DonMartin76** [comment]
OK! All good then.
