### ISSUE TITLE
The Portal should redirect requests on the http port to https

### ISSUE THREAD

**Issue by gganssauge** [Haufe-Lexware/wicked.haufe.io#24]
Most people tend to omit the scheme from urls nowadays and there are browser that don't retry on https automatically.
In this regard it would be nice if the portal could redirect requests on port 80 to port 443 automatically.

**Comment by DonMartin76** [comment]
This is highly depending on which type of load balancer/ingress you are using. Let's see if we can do this for the default simple configuration using `haproxy` though.

**Comment by DonMartin76** [comment]
I will not implement anything regarding this right; this has to be done in the TLS termination.
