### ISSUE TITLE
Any successful installs on GCP

### ISSUE THREAD

**Issue by rshrimp** [Haufe-Lexware/wicked.haufe.io#247]
I am trying to setup wicked as dev gateway on gcp.  All goes well following steps at https://wicked.haufe.io/gettingstarted.html.

What all do i need to do to get to localhost:3000 or 3333 for portal or kickstarter access.

If you have a doc that can point to this then that would be great.
Cheers

**Comment by DonMartin76** [comment]
Can you describe some more what you are trying to achieve with the developer setup on GCP, and what your setup looks like? The link you provided describes a local machine setup for a developer portal; if you're using GCP, I guess you are using a cloud VM where you issue these commands.

If this is the case, I also suppose you are using ssh to log in to that machine; if that is the case, you should be able to tunnel ports 3000 and/or 3333 to your local machine to achieve the same effect, i.e. using something like `ssh -L 3000:localhost:3000 -L 8000:localhost:8000 -L 3333:localhost:3333` <your gcp host>`. Port 8000 is the API gateway port.

**Comment by DonMartin76** [comment]
Closing this. If you still need help, feel free to re-open.
