### ISSUE TITLE
Support for k8s 1.16.x

### ISSUE THREAD

**Issue by adinaclaudia** [Haufe-Lexware/wicked.haufe.io#250]
K8s 1.16 deprecates some api versions that are still used in wicked. This makes it impossible to deploy wicked on a cluster >= 1.16 

See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for a short description. 

Beside the api version update, the selector field is mandatory for deployments and has to match the template.metadata.labels: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#deploymentspec-v1-apps

**Comment by DonMartin76** [comment]
Will address ASAP, thanks for pointing out!

**Comment by DonMartin76** [comment]
Fixed for 1.0.0-rc.12. Sorry for the delay.
