### ISSUE TITLE
Exposing Wicked - K8s cluster

### ISSUE THREAD

**Issue by roquecp** [Haufe-Lexware/wicked.haufe.io#254]
Hello!

At our company we are entering at the API era (finally), and we are evaluating some API Managers.
In one of our solutions we'll use Kong and that is one main reason why we are evaluating Wicked. And of course, because is open-source too :)

So, we managed to install the developer environment and the wicked-box, thanks to the good documentation we've found so far.
Until now, Wicked gave us somen good impressions and that is the reason why we tried to install Wicked in a K8s cluster.

We tried to install it on a "semi-production" environment, creating a k8s cluster on some AWS EC2 instances (we are not using EKS for this experiment).
After configuring some variables on HELM's `values.yaml`, we managed to install all pods on the cluster.
So far so good, but we are experiencing some difficulties on exposing Wicked, because until now, nobody here worked with Ingress on K8s.

Then how can we expose the Wicked API Manager from our cluster with Ingress? On our latest K8s clusters we exposed our aplication through ELB (service type LoadBalancer).
Wicked seems to work slightly different in this case giving we have 2 vhosts (portal.com and api.portal.com), am I right?

Maybe we've missed some point on documentation or it's a silly thing that we don't get it yet, but can you give some light on this final step?
We do not want to expose the service using a non-tested way, because that could lead to unexpected behaviours.

Keep up the good work and thanks in advance!

Best regards.
Roque Possamai.

**Comment by DonMartin76** [comment]
Hey there, happy you're finding your way through the documentation.

You're right in that wicked assumes that you have a working Ingress Controller, which does the SSL termination, installed in your cluster. The pattern is typically like this:

* Install an ingress controller, I recommend the nginx ingress controller
* This controller exposes itself on port 443 and 80 typically, creating a Load Balancer (and thus a public IP address)
* Make sure you have the correct SSL certificates stored as a secret inside your cluster, and add the names of the secrets to the values for the wicked Chart; having e.g. a wildcard certificate for this purpose is usually nice
* Point the DNS entries for the portal and the API gateway (e.g. developer.yourcompany.com and api.yourcompany.com), and make sure wicked thinks it uses the same DNS names
* The ingress controller will automatically route those DNS addresses to the portal and the API Gateway, respectively

This sometimes takes some fiddling if you're not used to it, but after that, it's rock solid typically.

If you have other specific questions, just ask here, and I'll try to answer as soon as I have time.

There should perhaps be more and better docs on especially this part.

**Comment by roquecp** [comment]
Ok, I'll try that.

> There should perhaps be more and better docs on especially this part.

That would be nice!

Thanks for the fast reply. 👍
