### ISSUE TITLE
Installing custom plugins on Kong

### ISSUE THREAD

**Issue by Alexanderdorow** [Haufe-Lexware/wicked.haufe.io#255]
I'm trying to install a custom plugin on Wicked Kong, but so far without success. I'm running the developer environment and already tried do the configuration inside the kong docker's container. Have you ever gone through the scenario of needing a custom plugin or knows how to install one?

**Comment by DonMartin76** [comment]
Ping @santokhsingh @maksimlikharev - aren’t you doing this? Can you give some pointers?

**Comment by maksimlikharev** [comment]
both vagrant and docker distributions of kong supports custom plugins configuration, 
please see the following:

https://github.com/Kong/kong-vagrant#environment-variables-and-configuration
https://registry.hub.docker.com/_/kong/

**Comment by santokhsingh** [comment]
More Info:

If you wish to link your custom plugin to the docker kong image which is being used by wicked you could do as follows. Here are the changes which I did to docker-compose.yml to hook my custom plugin    

  kong:
    image: wicked.kong:local
    depends_on:
    - "kong-database"
    links:
    - kong-database:kong-database
    security_opt:
    - seccomp:unconfined
    volumes:
    - **"/path/to/your/plugins/kong/plugins/<your-plugin>:/usr/local/share/lua/5.1/kong/plugins/<your-plugin>"**
    ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
    restart: unless-stopped
    environment:
    - "PROXY_SSL_KEY"
    - "PROXY_SSL_CERT"
    - "KONG_CUSTOM_PLUGINS=**<your-plugin>**"

**Comment by Alexanderdorow** [comment]
@santokhsingh It works, tnx for the help!!!
