### ISSUE TITLE
Idea: API Lifecycle support

### ISSUE THREAD

**Issue by DonMartin76** [Haufe-Lexware/wicked.haufe.io#26]
See also #25:

Deleting an abandonded API is perfectly fine and should be possible. Right now it's not that simple to do that right, as deleting an API requires all subscriptions to be deleted first. To make this simpler, the following functionality would be good:

* Add a possibility to "deprecate" an API, so that it's no longer possible to subscribe to it, but existing subscriptions are still in effect, as would documentation and Swagger still be available
* Add a "download subscriptions CSV" functionality which would let an Admin download a list of existing subscriptions for e-mailing actions announcing the retirement of an API
* Have an Admin functionality which lets an Admin delete all active subscriptions of an API
* In the kickstarter, add a "do you really know what you're doing" kind of alert in the kickstarter when deleting APIs.

Thoughts? Is this aiming too low, are there other big problems that need to be taken care of?

**Comment by TESAARON** [comment]
Hi Martin,

I think the admin control would be an important feature. Just gives super user access in case developer mistakes like this are made. Also the extra dialogue window to prompt the user would be good.

Aaron

**Comment by DonMartin76** [comment]
The problem you had with somebody acccidentally deleting an API will get a safety question; but as the kickstarter cannot know the state of the actual deployment, you will still need to keep in mind that you may still have existing subscriptions.

Sneak peeks (I decided this is important enough to have it in 0.10.0):

![api-lifecycle-support-in-portal](https://cloud.githubusercontent.com/assets/7326883/19959700/d91eab84-a1a8-11e6-892c-83c7caa60093.png)

![deprecated-api](https://cloud.githubusercontent.com/assets/7326883/19959730/016517b8-a1a9-11e6-9001-d385fe3541bf.png)

**Comment by DonMartin76** [comment]
Done.
