### ISSUE TITLE
Typescript compile failing due to @types/node update

### ISSUE THREAD

**Issue by shreyas-segu** [Haufe-Lexware/wicked.haufe.io#285]
Typescript compile step failing in these following modules
**Auth**- https://github.com/Haufe-Lexware/wicked.haufe.io/blob/1efadeabae7b7ccb4b17473e9aa5d0af60796adb/src/auth/package.json#L39
**Kong Adapter**- https://github.com/Haufe-Lexware/wicked.haufe.io/blob/1efadeabae7b7ccb4b17473e9aa5d0af60796adb/src/kong-adapter/package.json#L27
**node-sdk**- https://github.com/Haufe-Lexware/wicked.haufe.io/blob/1efadeabae7b7ccb4b17473e9aa5d0af60796adb/src/node-sdk/package.json#L28

Reference to the error
![image](https://user-images.githubusercontent.com/22915534/92381577-c4258300-f128-11ea-9448-f0d9a6e4c775.png)

Recently @types/node updated to https://www.npmjs.com/package/@types/node/v/10.17.29

Recommended to use absolute versions as typescript keeps releasing new features and might introduce new breaking changes to the syntax. Please let me know if you agree and I can create a PR.

**Comment by DonMartin76** [comment]
Sure, totally agree. I typically also like it most to use pinned versions.
