### ISSUE TITLE
installed but how do I access now?

### ISSUE THREAD

**Issue by peacemakr** [Haufe-Lexware/wicked.haufe.io#39]
Thanks for creating and sharing the portal.

I have installed it on a local VM and it seems its working (checked locally thru lynx) but how do I access it from other machines on the nerwork.

I am new to Docker and only installed for this project. 

here are the IPs that I have on the VM but my local network is 192.x, so other IPs cannot be used:
```
br-3a826545134d Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx 
          inet addr:172.x.x.x  Bcast:0.0.0.0  Mask:255.255.0.0
--

docker0   Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx  
          inet addr:172.x.x.x  Bcast:0.0.0.0  Mask:255.255.0.0
--

eth0      Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx  
          inet addr:192.168.x.x  Bcast:192.168.1.255  Mask:255.255.255.0
```

This is closer to a production setup, since you won't be running management system on localhost.

FYI: I used instructions at http://wicked.haufe.io/gettingstarted.html

**Comment by DonMartin76** [comment]
Hey peacemakr,

The IP you will need to access is the IP address of your docker host. IIf you installed docker in a VM (using which tool? VirtualBox? vmWare?) you will need to use that IP address. Depending on the setup of your virtualization tool it may be that it doesn't let you access port 443 through its firewall/NAT network setup, so it's really difficult to tell where to dig. In case you installed docker locally on your Windows or Mac OS X machine, you should be able to access the portal at localhost, but using a `Host` set to what you defined (for the example that's `portal.local`).

If you could share some more details on your docker setup, I might be able to assist. Running wicked in docker is perhaps not the simplest thing to start with though, you may want to read up on how docker works first, otherwise these things may be quite confusing.

Best regards, Martin

**Comment by peacemakr** [comment]
Thanks Martin.

I am using VirtualBox. There was a server running (and accessible) on port 443 before, so VM itself is not going to block that port. The eth0 interface is the actual VM's IP address and I've already tried accessing it from another host on the same network but without success. 

I think br-3a826545134d is the new interface that gets created when I run " docker-compose up -d". However, not sure why its using a different 172.x network for itself and for the container. Is it possible to configure the network in docker?

**Comment by peacemakr** [comment]
I restarted VM and now running container gives the following error

```
Creating network "wickeddeploysample_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-4824b0fed6e0 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
```
ran it as root.

**Comment by peacemakr** [comment]
I'm running this docker+wicked setup on a Ubuntu Trusty VM using Virtualbox. 
My development/test machine is separate from this VM.

You're right about reading up on Docker but thats too time consuming for testing a new product.

**Comment by DonMartin76** [comment]
OK, so the missing bits and pieces here would now be:

* You will need to set up port forwarding on Virtual Box for your Ubuntu VM (Change... -> Network -> Adapter 1 -> Port Forwarding -> 443 to 443)
* Add a local /etc/hosts entry for portal.local and api.portal.local pointing to the IP of the Virtual Box VM

Whenever you use HAproxy to do VHOST resolution like we do here, it's not enough to know the IP of the host, you also have to send the correct `Host: ` header with the request, which is automatically done by browsers, but only if it actually thinks the name is mapped to the IP (which is necessary here).

In other orchestration runtimes you may not need this, and instead use other types of load balancers, but this is how the default setup looks like.

**Comment by DonMartin76** [comment]
Did this work out, or did you run into other Docker issues?

**Comment by DonMartin76** [comment]
Closing this as I feel it's rather docker related than wicked related. A main prerequisite for running wicked is knowing your way around docker (or other orchestrations able to run docker containers). There are currently no plans on changing this to enable a more "traditional" deployment.
