### ISSUE TITLE
Preferred order of launching Wicked Portal micro services

### ISSUE THREAD

**Issue by Krieke** [Haufe-Lexware/wicked.haufe.io#46]
Is there a preferred order of launching Wicked Portal docker containers? We have seen that when a new "static" config was created with "kickstarter" that sometimes the other running docker containers should also be restarted when the new "Portal API" is launched.

**Comment by DonMartin76** [comment]
See also #36 and #38.

**Comment by DonMartin76** [comment]
Documentation and code will surface in 0.11.0 (due Monday).
