### ISSUE TITLE
Disaster Recovery Examples

### ISSUE THREAD

**Issue by d4nj0nes** [Haufe-Lexware/wicked.haufe.io#54]
I am interested in how to persist the dynamic data after we take down the docker images to update static config. Also of course, as a general disaster recovery technique
Adding examples on using deploy/export to create the backup and re applying that afterwards is mentioned here:
https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/disaster-recovery.md

**Comment by DonMartin76** [comment]
Hi there,

If you use the example compose file, you'll find that there are two volumes attached to the `portal-api` container: `portal-api-data-static` and `portal-api-data-dynamic`.

As long as you don't do a `docker-compose down` on the composition, the dynamic volume should just be able to remain on the docker host (note: this only works well in a single node docker environment).

Recreating the static configuration volume can then be done like this:

```
docker-compose stop portal-api
docker-compose rm portal-api portal-api-static-data
docker-compose build
docker-compose up -d
```

The other containers which rely on `portal-api` will automatically detect the changed configuration and will restart (i.e. quit and be restarted by `docker-compose` automatically).

For disaster recovery and backup scripts, check out the following repository:

https://github.com/Haufe-Lexware/wicked.portal-tools

In the `deploy` directory you can find sample implementations of both extracting the dynamic data, and importing dynamic data into a running setup.

**Comment by DonMartin76** [comment]
Closing this if there are no further questions.
