### ISSUE TITLE
Hide partner API endpoint information for visitors

### ISSUE THREAD

**Issue by hlgr360** [Haufe-Lexware/wicked.haufe.io#60]
You can assign APIs to a group, and only users belonging to that group will see the API. It’s also possible to assign a group to users who have validated their email address, so that only users with a valid email address can see the APIs. Additionally, you can leverage mapping ADFS groups to portal groups (not configured for this portal though) to automatically get certain users to see certain APIs, even though they have not (yet) logged in.

I suggest the following terminology:
- A visitor is someone visiting the APIm portal and is not logged in
- A user is someone who is logged-in
- Private APIs: actual APIs only visible to users, invisible to visitors
- Partner API's: actual APIs only visible to users, general API information is visible to visitors 
- Public API's: actual API is visible to visitors

I would like to hide the actual API end point for visitors looking at partner APIs. General information regarding the partner API should still be available, but not the actual endpoint.

**Comment by erotenberg** [comment]
This a very interesting enhancement request! We had something similar in mind. I am trying to figure out if your request would meet our use case. Can you please clarify how  'General Information' is defined in terms of the Partner API @hlgr360?

I interpret 'General Information' to mean that the visitor sees:

- The existence of the Partner API in the API Catalog (/api) (displays API name and short description)
- That the API Information page is accessible via direct URL, 
- The API information page displays the and that the API information page shows API name, long description, swagger documentation

Is above accurate?

**Comment by hlgr360** [comment]
Yes. The above is a good description.

**Comment by DonMartin76** [comment]
Happy to announce that this has landed in 0.12.5.
