### ISSUE TITLE
Customisation of Portal main files ?

### ISSUE THREAD

**Issue by pifleo** [Haufe-Lexware/wicked.haufe.io#66]
Hi @DonMartin76,

Thanks for that great work !
After a week fighting with all the doc and reading most of the code I finally found my way to deploy the project on AWS with a separate Kong Gateway.
The documentation contains a lot of things but I didn't know most of the tools used (Docker, Kubernetes, node.js ...).

We are now working on customizing the interface and we would love to make some change to the main files that are not editable in the static configuration folder.

If I get it, to add some global env variable we need to make changes to two/three projects:

 - `wicked.portal` where we want to use them
 - `wicked.portal-env` for the initial value of `globals.json`
 - `wicked.portal-kickstart` if we want a GUI to edit these params

Anywhere else ?

## Questions

1. [Design] We would like to make some important change to the layout on our side is there any easy way to do so ?
  I mean without rebuilding, hosting our own Docker images and staying close of your version to easily get updates.
  Could we have a mixin for the menu, for example, and how can we override it from our code ?
  We started some editions on a specific branch of a `wicked.portal` fork and we hot swipe the files for now:  [custom-gfp](https://github.com/GlobalFintechPlatform/wicked.portal/tree/custom-gfp)
  
  I don't know how this would be possible but something like for the `index.jade`, if I declare the same file as an existing one it's overrided by my version (Layout, content ...).
  
  I would be happy to propose PR that can work for you, us and other people if you have any though on that.

2. [Kong] Do you plan to release a Kong 0.10.1 version ? 
  I saw a lot of changes in their Changelog so maybe it's difficult at this point.

3. [Glyphicon] I tried to use some glyphicons on the page, some are not working, do you know which version is used ?
  I saw the loaded font is named `Glyphicon halflings` but I can't use all of the icon from this category I'm seeing here: http://glyphicons.com/. For example `halflings-key` is not working.
  Can we update the font in the next release? I'm not seeing the project where to do it.

4. [Applications] The friendly name for application is a little bit short the first one I typed was 25 char.
  If we can make it a bit longer that would be great

**Comment by DonMartin76** [comment]
Hi there! 

Regarding technicalities on your PR, please see my comment here:
https://github.com/Haufe-Lexware/wicked.portal/pull/3

Now to your questions:

1. Let's discuss more about which kinds of changes to which pages you would like to see. I can very well imagine that we can pull out some mixins e.g. for the API main page and offer to do that page as a jade file (like index). There are some other pages which may be a lot more tricky to get right, like the API specifics page and the Application/Applications page. Let's discuss what you would like to achieve. Perhaps we can offer multiple themes inside the main distro. I did try to make as much freely customizable as possible, but some things are fairly deeply entrenched in the portal logic, and there I did not (yet) do it. But I am definitely not saying no dogmatically.
2. Absolutely planned to go Kong 0.10.x at some point. I thought I'd give it another couple of minor releases; they had really large changes in the Admin API which I would like to let them stabilize first. Right now there's not much we're missing out on though, AFAIK.
3. Glyphicons are pulled in from Bootstrap, which is currently at version 3.3.7 (June 2016). Open a separate issue "Update Bootstrap" so we can track that separately please.
4. Sounds fair, and I don't see what speaks against it. Also a separate issue please.

Welcome aboard :-D

**Comment by pifleo** [comment]
I updated the PR.

1. If all my changes in the PR are ok, I have less much changes on my side
You can see a diff here: https://github.com/GlobalFintechPlatform/wicked.portal/pull/1/files

I’m starting to customize views on my versions of the portal and these changes are going to be different for each person deploying wicked. I'm still trying to think how you can easily allow that from the static configuration folder.

I’m seeing two options for now:
- Adding I18n files stored in the static folder to allow all fixed text to be changed and we could translate the portal at the same time. I don’t need multi language yet but could be useful to other. That will work when I only want to change the hard coded text from views but not enough in some cases.
If you know how to do the basic setup I can help extracting the text from view. I’m only starting with node.js/express.js by reading your code.
- Having a way to write a new file with the same name in our `static` configuration folder that as priority over the one from `wicked.portal` or override it
Maybe you could reproduce the same directory structure as the original portal.
An example is my version of `views/api.jade` (https://github.com/GlobalFintechPlatform/wicked.portal/pull/1/files#diff-f5457038816d37451a5603fd5d4d0931) which move things in the page. It is not really better than your presentation yet so I'm not going to push it to your repo.
So either have mixin to customize the page or a way to override it.

It's only html / css for today and I don't need to get new data from the back. I might need to add properties to some object later but we will see how to do that when it come.

2. Fine for me.

3. Bootstrap 3.3.7 seem to be the last stable version. They are working on a 4 (Alpha). 
I'm not opening the issue yet, I will look at which icons I need first.

4. Done

**Comment by DonMartin76** [comment]
Merged your PRs. I will open up an issue regarding the extension of the kickstarter for the new options. Right now, it's not all that important, as you have made all changes backwards compatible. Nonetheless, I think there should be documentation/guidance available on how to use them.
