### ISSUE TITLE
It's not possible to delete user verifications

### ISSUE THREAD

**Issue by achwie** [Haufe-Lexware/wicked.haufe.io#75]
# Description
It's not possible to delete user verifications (delete button simply does nothing), when logged in as admin in the wicked portal UI.

# Steps to reproduce
   1. Create a new user by registering in the "Sign Up" form
   2. Log in as admin and open the "Pending Verifications" page (you should see the pending verification from the user you just created)
   3. Check <wicked-config>/dynamic/verifications/_index.json (you should see the pending verification from the user you just created)
   4. Delete the pending verification of the new user using the "Delete" button on the "Pending Verifications" page (nothing will happen)
   5. Check <wicked-config>/dynamic/verifications/_index.json (you can also see that the pending verification is still there)
     => Expected: The pending verification will be deleted when deleting it in the admin UI
     => Actual: The pending verification is not deleted when deleting it in the admin UI

**Comment by DonMartin76** [comment]
Funny, yes, this is apparently not implemented.

**Comment by DonMartin76** [comment]
Fixed in wicked 1.0.0
