### ISSUE TITLE
Re. wicked.deploy.sample - Replace SHA1 Cert with SHA256 Cert

### ISSUE THREAD

**Issue by JaGeMo** [Haufe-Lexware/wicked.haufe.io#80]
I order to use common tools / browsers for testing purposes as well as security reasons the demo app wicked.deploy.sample should contain a SHA256 certificate instead of SHA1. Should be replaced in one of the releases/versions to come.

**Comment by achwie** [comment]
Created SHA256 certs and added them to the wicked.deploy.sample (see Haufe-Lexware/wicked.deploy.sample#2).
