### ISSUE TITLE
Provide support for Redis as session store for portal-ui

### ISSUE THREAD

**Issue by achwie** [Haufe-Lexware/wicked.haufe.io#83]
It would be great if the session store for the Portal-UI could be changed from file based (currently we use ``session-file-store``) to other options, such as Redis.

**Comment by DonMartin76** [comment]
Mostly done...

**Comment by DonMartin76** [comment]
How to use in wicked 0.12.0:

* New configurations/deployment setups which were configured with the Kickstarter default to using `redis` as a Session Store; it can be configured in the **IP Configuration** section of the Kickstarter

Adding to existing setups:

* Add a `redis` component to your setup, e.g. a docker container with  `redis:3.2.10-alpine`, which is the default for new setups, and make sure it's reachable as a service inside your deployment; the default URI is `portal-redis`, port `6739`, not using a password.
* Configure the "Session Store" to use `redis` in your **IP Configuration** section in the Kickstarter; this can also be configured differently for different environments (local testing, production,...), using environment variables. The default env var is `PORTAL_SESSIONSTORE_TYPE`, which should be set to `file` (the current non-scaling option) or `redis`.
* When starting the Kickstarter with your configuration, it will automatically add the options to your `globals.json` file, defaulting to `file` for existing configurations (to maintain backwards compatibility).
