### ISSUE TITLE
If user is logged in, the email validation does not have immediate effect

### ISSUE THREAD

**Issue by szmiklos** [Haufe-Lexware/wicked.haufe.io#88]
### Problem
If I sign up on the portal i will be navigated to the page 'applications', here is a message like "you have to validate your email". I keep open this page and go validate my email. When im done i navigate back to the 'applications' page and refresh but nothing happens, i just see the same message ("you have to validate your email").
### Suggestion
When you validate your email, should save this state immediately. My suggestion: should set user's validated property true in to the user session in function handleEmailVerification() (portal/routes/verification.js).

**Comment by DonMartin76** [comment]
It probably doesn't get re-read until you re-login, which is not quite desired behavior, I agree. Will look into it.

**Comment by vivekpd15** [comment]
+1 @DonMartin76 Any updates on this? Would really appreciate any kind of help on this.

**Comment by DonMartin76** [comment]
The code has evolved a real great bunch from the 0.12 release in the mean time, and this portion is something which will go out of the portal implementation completely (and into the default authorization server). I'll see if I can throw in an intermediate release 0.12.2 before we can go for a 1.0.0 beta release. There are a couple of other candidates for such a release.

**Comment by DonMartin76** [comment]
OK, this is a little stupid, as this is quite interwoven with passport.js. Passport handles everything by a little magic, and thus the user settings are copied into the `req.user` property during one of the middleware handlers in the generic code. Updating the `validated` property here wouldn't do anything, unfortunately, so I fixed this via a small hack which updates the internal session state of passport.

I strongly dislike this, but it currently works.
