### ISSUE TITLE
Unable to deploy locally on Windows

### ISSUE THREAD

**Issue by TESAARON** [Haufe-Lexware/wicked.haufe.io#9]
Hello,

I have followed all the steps in the following file for local deployment of the portal:
https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/deploying-locally.md

However, when I go to the url: https://portal.local/ I get the following screen saying: "The Portal is not yet fully initialized. Please reload in a couple of seconds." However nothing happens when I reload this screen.

![capture](https://cloud.githubusercontent.com/assets/10795276/18756221/0225d350-80e7-11e6-99c8-65bd971c4b24.PNG)

Any ideas how I could rectify this issue?

Many thanks.

**Comment by DonMartin76** [comment]
Have you managed to check the logs? This is the behavior the Portal exposes if the Portal API does not manage to start (for some reason). Usually, the API will tell you exactly what's wrong, and I suspect it's lacking one or more environment variables.

If you do a `docker-compose up` without the `-d` parameter, compose will output the logs to `stdout`, and as compose tries to restart stopped containers, you will repeatedly see the `wicked.portal-api` container failing (supposedly), stating each time why fails.

Please report what your issue was so that I can amend the documentation.

/Martin

**Comment by TESAARON** [comment]
Hi Martin,

I am including here the error log when I run docker-compose up. 

[error_log_file.txt](https://github.com/Haufe-Lexware/wicked.haufe.io/files/489261/error_log_file.txt)

It seems to be logging errors on the environment variables that I have set in the localhost environment. I also attach a screenshot of the environment variables that I configured in kickstarter for the localhost.

![capture](https://cloud.githubusercontent.com/assets/10795276/18781174/9ef1761c-8178-11e6-9d7f-b101db1277d6.PNG)

Let me know what you think.

Aaron

**Comment by DonMartin76** [comment]
The API says it can't find the localhost.json file. Try to tear down the entire environment using `docker-compose down`, and redeploy. When deploying (even locally) a new static configuration, it's important that you remove both the `portal-api` and `portal-api-data-static` containers to make docker pick up the new configuration (it won't overwrite them).

Btw., I just realized that the configuration `localhost` should not be used for this use case (misleading documentation). Try to create a new environment called `local` or `dev` similar (just not `localhost`); if you create a `localhost` environment, some things are configured automatically in a way which does not match the docker setup (see https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/development-environment.md) and is intended for local development of the wicked components themselves.

I will adapt the documentation accordingly, thanks for reporting.

**Comment by DonMartin76** [comment]
I have found an issue with the docker images... will get back to this in a couple of minutes.

**Comment by TESAARON** [comment]
Many thanks Martin. I will try this and let you know how it goes.

**Comment by TESSaranya** [comment]
Hi Martin, 

I am working with Aaron in this. Just a query after pulling haufelexware/wicked.portal-api , should use the command ## **docker run -it --rm -v /path/to/repo:/var/portal-api -p 3333:3333 haufelexware/wicked.portal-api --new**  ?? if not, could you please let us know the steps after this  docker pull??

**Comment by DonMartin76** [comment]
The docker pull just updates the image for `wicked.portal-api`; the API is used inside the `docker-compose.yml` file, so you would only need to do the following:

```bash
$ cd /path/to/your/repo
$ docker-compose down # this removes all containers (including users, so beware)
$ docker-compose up # restart the thing
```

Then navigate to https://portal.local, and things should be fine.

**Comment by TESSaranya** [comment]
When executed with docker-compose up. I got the following response. Can you let me know, what is the issue.

[log.txt](https://github.com/Haufe-Lexware/wicked.haufe.io/files/489730/log.txt)

**Comment by DonMartin76** [comment]
The main error is: 

```
Error: portal-env: Could not find environment file: /var/portal-api/static/env/localdev.json
```

This is most likely due to the fact that once a static volume container is built, it will be re-used. The Portal API has not picked up the changed configuration repository. This is described at the continuous deployment documentation page: https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/continuous-deployment.md

Short version of that page: Your problems will most probably go away by doing the following:

```bash
$ cd /path/to/repo
$ docker-compose rm -fv portal-api-data-static # remove static config container
$ docker-compose build
$ docker-compose up -d --remove-orphans portal-api-data-static # start it once
$ docker-compose up -d --remove-orphans --force-recreate # start the portal
```

**Comment by TESAARON** [comment]
Hi Martin,

This fix worked perfectly. We now have a working api-portal that we can configure using kickstarter. I will keep you updated if we have any more issues!

Many thanks for your time,
Aaron

**Comment by DonMartin76** [comment]
OK, glad to hear that! This is not even a "wicked" issue, but rather docker usage, which admittedly looks strange. Will at times work on the documentation of that thing. The "deploying locally" guide does not mention what to do when you want to refresh the configuration.

**Comment by DonMartin76** [comment]
Closing.
