### ISSUE TITLE
Dynamic data volume export using wicked.portal-tools not working

### ISSUE THREAD

**Issue by himansingh** [Haufe-Lexware/wicked.haufe.io#93]
I am trying to export the dynamic data volume using the commands given in [wicked.portal-tools](https://github.com/apim-haufe-io/wicked.portal-tools).
The portal is built using the wicked sample portal on docker.
I have created a **demo app** which has subscription of  **demo api**. 

I used following commands :
`$ git clone https://github.com/Haufe-Lexware/wicked.portal-tools`
`$ cd wicked.portal-tools`
`$ npm install`
`...`
`$ export PORTAL_CONFIG_KEY=<the deployment key of your API Portal instance>`
`$ node deploy/export-config.js https://api.portal.local/deploy/v1 archive.tgz.enc`

and got these logs 
![screenshot from 2017-11-07 16-09-48](https://user-images.githubusercontent.com/29802866/32489772-0cf4c866-c3d7-11e7-9361-baf437733d7b.png)

In **Kong service** the virtual host is api.portal.local
"VIRTUAL_HOST=https://api.portal.local:443"

and in **Portal service** the virtual host is portal.local
"VIRTUAL_HOST=https://portal.local:443"

Any help would be very much appreciated!

**Comment by DonMartin76** [comment]
Hello @himansingh,

The deployment API is deprecated and will be removed in one of the upcoming updates.

We advise to use one of the following approaches instead: For the dynamic data,...

* Use externalized storage, such as an NFS or other similar storage
* Use a docker volume like before, but don't use the deployment API to retrieve the dynamic configuration, but rather use `docker cp` to get the data out from the portal API container; this approach comes the nearest to the deployment API, but is a lot easier to implement in scripts.

You are right in that the documentation needs an update.

Best regards,
Martin

**Comment by himansingh** [comment]
That should do the work. Thank you @DonMartin76 for such a quick response. :)

**Comment by DonMartin76** [comment]
You're welcome. Closing this for now, feel free to reopen if you need more information.
