### ISSUE TITLE
Unable to deploy a custom API extending wicked

### ISSUE THREAD

**Issue by himansingh** [Haufe-Lexware/wicked.haufe.io#94]
Hi,
I am working on adding a new feature in portal system that allows users to reset their API key. So, I tried writing a custom API . For testing purpose I just used the following code in app.js file, but it didn't work. 

`app.get('/resetapikey/:appId', function(req, res) { 
   debug("------ you sent request to /resetapikey ----");
    res.status(200).send("IT WORKS");                                                       
});`

I also tried similar stuff in routes/applications.js but that didn't work either. Looks like either I am making changes in wrong file or the changes are not getting deployed. Can you please tell me what am I doing wrong.

Any help would be very much appreciated. Thanks!

**Comment by himansingh** [comment]
@DonMartin76, 
Thank you for the response once again. I wanted to generate a new API key without affecting the subscriptions and plan.

The problem was that I was editing node code of `portal-api` container only. I figured out my mistake and wrote the logic on node code of `portal` container as well. It works fine now. I am able to reset the API key :)

**Comment by DonMartin76** [comment]
OK. Still, let's align on the use case description so that this could also go into the main trunk?

**Comment by vivekpd15** [comment]
@DonMartin76 First of all, great work on this project. 

I am also interested in a similar use case.

In my opinion, the main trunk can have these additions:

1) Option to reset the API key on the fly. As you earlier stated, I would as well love to see 2 API keys working simultaneously, but if this is tough then at the very least there should be an option to reset the key without unsubscribing. A user may want to reset his security key at any point of time owing to security reasons.

2) Also, it would be great if you can include changing plans on the fly into the main trunk. So if a user is on a basic plan and wants to upgrade to a premium one, he should be able to do so, without unsubscribing or requiring any api key change.

**Comment by DonMartin76** [comment]
@vivekpd15 Would you be interested in creating a short spec on how each of these points could effectively work? At least from a user's and admin's perspective. Both things require quite some changes and are obviously very security relevant (No. 2 in the end allows for patching a subscription, and the thing might need to go via the approval workflow, so it's not trivial).

If you feel inclined to do so, feel free to create new issues ("Feature: ...") in this repo.

**Comment by DonMartin76** [comment]
Closed due to inactivity.
